[package]
name = "generated_parser"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
bumpalo = "2.6.0"

[lib]
name = "generated_parser"
path = "src/lib.rs"
