[workspace]

[package]
name = "collect_handler_info"
version = "0.0.1"
license = "MIT/Apache-2.0"

[dependencies]
clap = "^2"
syn = { version = "1", default-features = false, features = ["full", "parsing"] }

[[bin]]
name = "collect_handler_info"
path = "src/main.rs"
